import { useCallback, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, Check, Clock3, Code2, ShieldCheck, UsersRound, MessageSquareText, Rocket } from 'lucide-react'
import LandingSeo from '../components/landing/LandingSeo.jsx'
import LandingHeader from '../components/landing/LandingHeader.jsx'
import LandingFooter from '../components/landing/LandingFooter.jsx'
import LeadForm from '../components/landing/LeadForm.jsx'
import CalendlyButton, { openCalendly } from '../components/landing/CalendlyButton.jsx'

const proof = [[Clock3, '24 hours', 'to a focused shortlist'], [Code2, 'React · Node · Python', 'modern product-stack experience'], [ShieldCheck, 'Interview first', 'technical fit before engagement']]
const capabilities = [['Product engineering', 'Customer-facing products, component systems and performance-minded delivery.'], ['Backend & integrations', 'APIs, services, databases and practical systems integration.'], ['Cloud-ready delivery', 'AWS, Azure, CI/CD and observability awareness for reliable releases.'], ['Flexible team extension', 'One specialist or a delivery-ready pod aligned to your roadmap.']]
const process = [[UsersRound, 'Tell Us What You Need', 'Share the role, seniority, stack and delivery context.'], [ShieldCheck, 'Receive Vetted Profiles', 'We screen relevant talent and send a focused shortlist.'], [MessageSquareText, 'Interview Your Shortlist', 'Meet suitable engineers before choosing an engagement.'], [Rocket, 'Start Building', 'Onboard quickly and begin delivery with your new team.']]
const faqs = [['How quickly can I receive profiles?', 'After understanding your requirements, we can share a focused shortlist within 24 hours.'], ['Can I interview developers before hiring?', 'Yes. You meet shortlisted engineers before deciding on an engagement.'], ['Can you support our existing stack?', 'Yes. Matching can be focused on your frontend, backend, cloud, data and delivery context.'], ['Can we start with one engineer?', 'Yes. You can begin with one role and extend capacity as the roadmap changes.']]

export default function SoftwareDevelopersCampaign({ meta, content }) {
  const [openFaq, setOpenFaq] = useState(0)
  const scrollToForm = useCallback(() => document.getElementById('software-lead-form')?.scrollIntoView({ behavior: 'smooth', block: 'center' }), [])
  return <>
    <LandingSeo meta={meta} content={content} />
    <LandingHeader onGetProfiles={scrollToForm} onBookCall={openCalendly} primaryCta="Get profiles" secondaryCta="Book a 30-minute call" />
    <main className="bg-slate-50 text-ething-ink">
      <section className="relative overflow-hidden bg-[#061b2d] pt-28 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_28%,rgba(45,211,195,.24),transparent_28%),linear-gradient(135deg,#061b2d,#0a4053)]"/><div className="relative mx-auto grid max-w-6xl gap-10 px-4 pb-16 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8"><div className="py-8"><p className="mb-5 text-sm font-bold uppercase tracking-[.16em] text-teal-300">eThing Solutions · Software engineering talent</p><h1 className="max-w-3xl font-[family:var(--font-display)] text-4xl font-bold leading-tight sm:text-5xl">Hire software developers for the product work your roadmap needs next.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-200">Tell us the skills, seniority and delivery context you need. We’ll share suitable, pre-vetted developer profiles in 24 hours.</p><div className="mt-7 flex flex-wrap gap-2">{['NDA protected', 'Global timezone overlap', 'Flexible engagement'].map(item => <span key={item} className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-100"><Check className="mr-1 inline h-3.5 w-3.5 text-teal-300"/>{item}</span>)}</div><div className="mt-8"><CalendlyButton variant="outline">Book a 30-minute call</CalendlyButton></div></div><div id="software-lead-form" className="self-center rounded-2xl bg-white p-5 text-ething-ink shadow-2xl sm:p-7"><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Start here</p><h2 className="mt-2 text-2xl font-bold">Get vetted software developer profiles.</h2><p className="mt-2 text-sm text-slate-600">Share the brief and we’ll match the right experience to it.</p><div className="mt-5"><LeadForm cta="Get Developer Profiles" compact formId="software-developer-profiles" /></div></div></div></section>
      <section className="border-b border-slate-200 bg-white py-8 text-center"><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-500">Companies we have worked with</p><div className="mx-auto mt-4 flex max-w-5xl flex-wrap justify-center gap-3">{['PostHog','Plausible','Buffer','ConvertKit','Toggl','Hotjar','Typeform','Ghost'].map(name => <span key={name} className="rounded-lg border border-slate-200 bg-slate-50 px-5 py-3 text-sm font-bold text-slate-600">{name}</span>)}</div></section>
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.16em] text-teal-700">Software developer proof</p><h2 className="mx-auto mt-3 max-w-3xl text-center font-[family:var(--font-display)] text-3xl font-bold sm:text-4xl">Start with context, not a pile of resumes.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{proof.map(([Icon, title, copy]) => <motion.article whileHover={{ y:-6 }} key={title} className="rounded-2xl border border-teal-100 bg-white p-7 shadow-sm"><Icon className="h-9 w-9 text-teal-600"/><h3 className="mt-7 text-2xl font-bold text-teal-700">{title}</h3><p className="mt-2 text-slate-600">{copy}</p></motion.article>)}</div></section>
      <section className="bg-white px-4 py-16 sm:px-6 lg:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.16em] text-teal-700">Capabilities</p><h2 className="mx-auto mt-3 max-w-4xl text-center font-[family:var(--font-display)] text-3xl font-bold sm:text-4xl">Software delivery capabilities for the work your roadmap needs next.</h2><div className="mx-auto mt-10 grid max-w-6xl gap-5 sm:grid-cols-2 lg:grid-cols-4">{capabilities.map(([title, copy], index) => <motion.article whileHover={{ y:-5 }} key={title} className="rounded-2xl border border-slate-200 p-6"><span className="text-xs font-bold text-teal-700">0{index+1}</span><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{copy}</p></motion.article>)}</div></section>
      <section className="bg-[#073847] px-4 py-16 text-white sm:px-6 lg:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.16em] text-teal-300">Our Process</p><h2 className="mt-3 text-center font-[family:var(--font-display)] text-3xl font-bold sm:text-4xl">A focused route from brief to delivery.</h2><div className="mx-auto mt-10 grid max-w-6xl gap-5 md:grid-cols-2 lg:grid-cols-4">{process.map(([Icon, title, copy], index) => <motion.article whileHover={{ scale:1.03 }} key={title} className="relative rounded-2xl border border-teal-200/25 bg-white/5 p-6"><Icon className="absolute right-5 top-5 h-8 w-8 text-teal-200"/><span className="text-sm font-bold text-teal-200">0{index+1}</span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-200">{copy}</p></motion.article>)}</div></section>
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.16em] text-teal-700">Client stories</p><h2 className="mt-3 text-center font-[family:var(--font-display)] text-3xl font-bold">Trusted by teams that need dependable delivery capacity.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[['Global fintech','85 employees','2 senior engineers selected'],['Healthtech scale-up','65 employees','Product delivery team extended'],['E-commerce platform','220 employees','Flexible engagement']].map(([industry,size,outcome]) => <motion.article whileHover={{ y:-6 }} key={industry} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><span className="inline-flex rounded-full bg-teal-50 px-3 py-1 text-xs font-bold uppercase tracking-wider text-teal-700">Verified engagement</span><h3 className="mt-5 text-lg font-bold">{industry}</h3><p className="mt-1 text-sm text-slate-500">{size}</p><p className="mt-5 leading-relaxed text-slate-600">“The shortlist was focused, technically credible and easy for our team to assess.”</p><p className="mt-5 text-sm font-bold text-teal-700">{outcome}</p></motion.article>)}</div></section>
      <section className="bg-white px-4 py-16 sm:px-6 lg:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.16em] text-teal-700">FAQs</p><h2 className="mt-3 text-center font-[family:var(--font-display)] text-3xl font-bold">Questions, answered.</h2><div className="mx-auto mt-8 max-w-3xl divide-y divide-slate-200 rounded-2xl border border-slate-200">{faqs.map(([q,a],index)=><article key={q}><button onClick={()=>setOpenFaq(openFaq===index?-1:index)} className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left font-bold">{q}<span className="text-teal-700">{openFaq===index?'−':'+'}</span></button>{openFaq===index&&<p className="px-6 pb-5 leading-relaxed text-slate-600">{a}</p>}</article>)}</div></section>
    </main><LandingFooter />
  </>
}
